name: "Terraform"
on:
  push:
    branches: ["main", "master"]
    paths: ["src/**"]
  workflow_dispatch: 

jobs:
  terraform: 
    name: "Terraform apply"
    runs-on: "ubuntu-latest"
    steps: 
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

              
